-- PostgreSQL migration for legacy users and audit_logs keys.
-- Run this against the existing database after making a backup.
--
-- What it fixes:
-- 1. public.users is a legacy table and may not have PRIMARY KEY/identity.
-- 2. public.audit_logs may have been created before schema.sql received
--    "GENERATED ALWAYS AS IDENTITY"; CREATE TABLE IF NOT EXISTS does not
--    repair existing columns.
-- 3. public.audit_logs is polymorphic: actor_id/entity_id can point to
--    different tables, so normal FOREIGN KEY constraints are intentionally
--    not added here.

BEGIN;

DO $$
DECLARE
    duplicate_id_count bigint;
    duplicate_logins text;
    identity_flag text;
    default_expr text;
    next_id bigint;
    sequence_name text;
BEGIN
    IF to_regclass('public.users') IS NULL THEN
        RAISE NOTICE 'Table public.users does not exist, skipped.';
        RETURN;
    END IF;

    SELECT COUNT(*)
    INTO duplicate_id_count
    FROM (
        SELECT id
        FROM public.users
        GROUP BY id
        HAVING COUNT(*) > 1
    ) duplicated_ids;

    IF duplicate_id_count > 0 THEN
        RAISE EXCEPTION 'Cannot add PRIMARY KEY to public.users: duplicate id values exist.';
    END IF;

    IF EXISTS (SELECT 1 FROM public.users WHERE id IS NULL) THEN
        RAISE EXCEPTION 'Cannot add PRIMARY KEY to public.users: id contains NULL values.';
    END IF;

    ALTER TABLE public.users ALTER COLUMN id SET NOT NULL;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.users'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
    END IF;

    SELECT
        a.attidentity,
        pg_get_expr(d.adbin, d.adrelid)
    INTO identity_flag, default_expr
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d
        ON d.adrelid = a.attrelid
       AND d.adnum = a.attnum
    WHERE a.attrelid = 'public.users'::regclass
      AND a.attname = 'id'
      AND NOT a.attisdropped;

    IF COALESCE(identity_flag, '') = '' AND default_expr IS NULL THEN
        ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.users;
    SELECT pg_get_serial_sequence('public.users', 'id') INTO sequence_name;

    IF sequence_name IS NOT NULL THEN
        EXECUTE format('SELECT setval(%L::regclass, %s, false)', sequence_name, next_id);
    END IF;

    SELECT string_agg(login, ', ' ORDER BY login)
    INTO duplicate_logins
    FROM (
        SELECT login
        FROM public.users
        GROUP BY login
        HAVING COUNT(*) > 1
        LIMIT 20
    ) duplicated_logins;

    IF duplicate_logins IS NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_index i
            JOIN pg_attribute a
              ON a.attrelid = i.indrelid
             AND a.attnum = ANY(i.indkey)
            WHERE i.indrelid = 'public.users'::regclass
              AND i.indisunique
              AND a.attname = 'login'
        ) THEN
            ALTER TABLE public.users ADD CONSTRAINT users_login_key UNIQUE (login);
        END IF;
    ELSE
        RAISE NOTICE 'UNIQUE public.users(login) skipped. Resolve duplicate logins first: %', duplicate_logins;
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_login ON public.users(login)';
    END IF;
END $$;

DO $$
DECLARE
    duplicate_id_count bigint;
    identity_flag text;
    default_expr text;
    invalid_actor_types text;
    next_id bigint;
    sequence_name text;
BEGIN
    IF to_regclass('public.audit_logs') IS NULL THEN
        RAISE NOTICE 'Table public.audit_logs does not exist, skipped.';
        RETURN;
    END IF;

    SELECT COUNT(*)
    INTO duplicate_id_count
    FROM (
        SELECT id
        FROM public.audit_logs
        GROUP BY id
        HAVING COUNT(*) > 1
    ) duplicated_ids;

    IF duplicate_id_count > 0 THEN
        RAISE EXCEPTION 'Cannot add PRIMARY KEY to public.audit_logs: duplicate id values exist.';
    END IF;

    IF EXISTS (SELECT 1 FROM public.audit_logs WHERE id IS NULL) THEN
        RAISE EXCEPTION 'Cannot add PRIMARY KEY to public.audit_logs: id contains NULL values.';
    END IF;

    ALTER TABLE public.audit_logs ALTER COLUMN id SET NOT NULL;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.audit_logs'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
    END IF;

    SELECT
        a.attidentity,
        pg_get_expr(d.adbin, d.adrelid)
    INTO identity_flag, default_expr
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d
        ON d.adrelid = a.attrelid
       AND d.adnum = a.attnum
    WHERE a.attrelid = 'public.audit_logs'::regclass
      AND a.attname = 'id'
      AND NOT a.attisdropped;

    IF COALESCE(identity_flag, '') = '' AND default_expr IS NULL THEN
        ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.audit_logs;
    SELECT pg_get_serial_sequence('public.audit_logs', 'id') INTO sequence_name;

    IF sequence_name IS NOT NULL THEN
        EXECUTE format('SELECT setval(%L::regclass, %s, false)', sequence_name, next_id);
    END IF;

    SELECT string_agg(actor_type, ', ' ORDER BY actor_type)
    INTO invalid_actor_types
    FROM (
        SELECT DISTINCT actor_type
        FROM public.audit_logs
        WHERE actor_type NOT IN ('user', 'admin', 'system')
    ) invalid_values;

    IF invalid_actor_types IS NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'public.audit_logs'::regclass
              AND conname = 'audit_logs_actor_type_check'
        ) THEN
            ALTER TABLE public.audit_logs
                ADD CONSTRAINT audit_logs_actor_type_check
                CHECK (actor_type IN ('user', 'admin', 'system'));
        END IF;
    ELSE
        RAISE NOTICE 'CHECK public.audit_logs(actor_type) skipped. Invalid values: %', invalid_actor_types;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.audit_logs'::regclass
          AND conname = 'audit_logs_changes_is_object_check'
    ) THEN
        ALTER TABLE public.audit_logs
            ADD CONSTRAINT audit_logs_changes_is_object_check
            CHECK (jsonb_typeof(changes) = 'object');
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor
    ON public.audit_logs(actor_type, actor_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action
    ON public.audit_logs(action);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
    ON public.audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
    ON public.audit_logs(entity_table, entity_id);

COMMIT;

-- Optional manual cleanup if you want public.users(login) to be UNIQUE and
-- duplicate logins exist. Review the result before running this block.
--
-- WITH ranked_users AS (
--     SELECT
--         id,
--         login,
--         ROW_NUMBER() OVER (PARTITION BY login ORDER BY id) AS duplicate_number
--     FROM public.users
-- )
-- UPDATE public.users u
-- SET login = ranked_users.login || '_duplicate_' || u.id
-- FROM ranked_users
-- WHERE ranked_users.id = u.id
--   AND ranked_users.duplicate_number > 1;
--
-- ALTER TABLE public.users ADD CONSTRAINT users_login_key UNIQUE (login);
